package liquer.alchemy.xmlcrypto.crypto.xml.saml.core;

public enum AssertionElement {
    UNDEFINED,
    ASSERTION,
    ISSUER,
    SUBJECT, SUBJECT_CONFIRMATION,
    CONDITIONS, AUDIENCE_RESTRICTION, AUDIENCE,
    ATTRIBUTE_STATEMENT, ATTRIBUTE, ATTRIBUTE_VALUE,

    // Signature
    SIGNATURE,
    CANONICALIZATION_METHOD,
    SIGNATURE_METHOD,
    SIGNED_INFO,
    REFERENCE,
    DIGEST_METHOD,
    DIGEST_VALUE,
    TRANSFORMS,
    TRANSFORM,
    INCLUSIVE_NAMESPACES,
    SIGNATURE_VALUE,
    KEY_INFO,
    X_509_DATA,
    X_509_CERTIFICATE,
    X_509_ISSUER_SERIAL,
    X_509_ISSUER_NAME,
    X_509_SERIAL_NUMBER
}
