//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.01 at 08:51:34 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:SAML:2.0:assertion",
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI="http://www.w3.org/2000/09/xmldsig#", prefix=""),
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI="urn:oasis:names:tc:SAML:2.0:assertion", prefix="saml"),
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wsswssecurity-secext-1.0.xsd", prefix="wsse"),
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI="http://www.w3.org/2003/05/soap-envelope", prefix="soap")
        })
package liquer.alchemy.xmlcrypto.crypto.xml.saml.jaxb.model;

